version: '3'

services:
  github-api:
    image: node:10-alpine
    container_name: github-api
    user: node
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    command: sh /var/www/app/bootstrap.sh
    ports:
      - 8080:8080
